Repository Roche/crmPack, pull requests merged in 2022-10, with the labels that each got.

#371 Closes #361
  .lintr
  R/Model-validity.R
  tests/testthat/test-Model-validity.R
Labels: bug, high priority

#376 Closes #375
  .lintr
  DESCRIPTION
  NAMESPACE
  R/Data-class.R
  R/Data-validity.R
  R/Model-class.R
  R/Model-validity.R
  R/Rules-methods.R
  R/Rules-validity.R
  R/Simulations-class.R
  R/Simulations-methods.R
  R/helpers.R
  R/helpers_model.R
  R/helpers_rules.R
  _pkgdown.yaml
  man/approximate.Rd
  man/biomarker.Rd
  man/dose.Rd
  man/doseFunction.Rd
  man/efficacy.Rd
  man/efficacyFunction.Rd
  man/enable_logging.Rd
  man/examine.Rd
  man/fit.Rd
  man/fitGain.Rd
  man/fitPEM.Rd
  man/gain.Rd
  man/matchTolerance.Rd
  man/maxDose.Rd
  man/maxSize.Rd
  man/mcmc.Rd
  man/minSize.Rd
  man/nextBest.Rd
  man/plotDualResponses.Rd
  man/plotGain.Rd
  man/prob.Rd
  man/probFunction.Rd
  man/size.Rd
  man/stopTrial.Rd
  man/v_data_objects.Rd
  man/v_increments.Rd
  man/v_mcmcoptions_objects.Rd
  man/v_model_objects.Rd
  man/v_model_params.Rd
  man/v_next_best.Rd
  man/v_stopping.Rd
  man/windowLength.Rd
  tests/testthat/test-Data-validity.R
  vignettes/crmPack-jss-paper.Rnw
  vignettes/example.Rnw
Labels: cleanup

#381 Closes #362
  NEWS.md
  vignettes/migration_from_the_old_crmPack.Rmd
Labels: cleanup

#389 Closes #387
  R/Rules-class.R
  R/Rules-validity.R
  man/StoppingLowestDoseHSRBeta-class.Rd
  tests/testthat/test-Rules-class.R
  tests/testthat/test-Rules-validity.R
Labels: cleanup

#391 Closes #388
  NEWS.md
  R/Rules-class.R
  R/Rules-methods.R
  R/Rules-validity.R
  _pkgdown.yaml
  examples/Rules-class-StoppingTargetBiomarker.R
  man/StoppingTargetBiomarker-class.Rd
  man/StoppingTargetBiomarker.Rd
  man/v_stopping.Rd
  tests/testthat/test-Rules-class.R
  tests/testthat/test-Rules-validity.R
Labels: cleanup

#369 Closes #363 assert_true checks not correct. After discussion the whole method for…
  R/mcmc.R
Labels: bug, cleanup

#396 Closes #393
  R/Model-class.R
  R/Model-validity.R
  man/FractionalCRM-class.Rd
  man/OneParExpNormalPrior-class.Rd
  man/mcmc.Rd
  tests/testthat/_snaps/Model-class.md
  tests/testthat/_snaps/Model-methods.md
  tests/testthat/helper-model.R
  tests/testthat/test-Model-class.R
  tests/testthat/test-Model-validity.R
Labels: bug

#400 Closes #397
  NEWS.md
  R/checkmate.R
  man/check_probabilities.Rd
  tests/testthat/test-checkmate.R
Labels: enhancement

#402 Closes #399
  R/Model-class.R
  R/Model-validity.R
  tests/testthat/test-Model-class.R
  tests/testthat/test-Model-validity.R
Labels: enhancement

#409 Closes #395
  NEWS.md
  R/Rules-class.R
  R/Rules-methods.R
  R/Rules-validity.R
  _pkgdown.yaml
  examples/Rules-class-StoppingList.R
  examples/Rules-method-stopTrial-StoppingList.R
  man/StoppingList-class.Rd
  man/StoppingList.Rd
  man/stopTrial.Rd
  man/v_stopping.Rd
  tests/testthat/helper-rules.R
  tests/testthat/test-Rules-class.R
  tests/testthat/test-Rules-validity.R
Labels: cleanup

#411 Closes #410
  NEWS.md
  R/Rules-class.R
  R/Rules-methods.R
  R/Rules-validity.R
  _pkgdown.yaml
  examples/Rules-class-StoppingAll.R
  examples/Rules-class-StoppingList.R
  man/StoppingAll-class.Rd
  man/StoppingAll.Rd
  man/StoppingList-class.Rd
  man/v_stopping.Rd
  tests/testthat/test-Rules-class.R
  tests/testthat/test-Rules-validity.R
Labels: cleanup
