Repository Roche/crmPack, pull requests merged in 2023-01, with the labels that each got.

#463 Closes #154
  NAMESPACE
  NEWS.md
  R/Model-methods.R
  R/helpers.R
  _pkgdown.yaml
  man/h_null_if_scalar.Rd
  tests/testthat/test-Model-methods.R
  tests/testthat/test-helpers.R
Labels: cleanup

#466 Closes #196
  R/Data-methods.R
  R/Model-class.R
  R/mcmc.R
  man/getEff.Rd
  tests/testthat/test-Data-methods.R
Labels: cleanup

#468 Closes #462
  R/Model-methods.R
  tests/testthat/helper-samples.R
  tests/testthat/test-Model-methods.R
Labels: cleanup

#374 319improve read me
  .Rbuildignore
  DESCRIPTION
  NAMESPACE
  R/crmPack-package.R
  R/utils-pipe.R
  README.Rmd
  README.md
  inst/WORDLIST
  man/check_probabilities.Rd
  man/check_probability.Rd
  man/check_probability_range.Rd
  man/h_test_named_numeric.Rd
  man/nextBest.Rd
  man/pipe.Rd
  vignettes/crmPack-jss-paper.Rnw
  vignettes/trial_analysis.Rmd
  vignettes/trial_definition.Rmd
  vignettes/trial_simulation.Rmd
  vignettes/vignettes.bib
Labels: documentation

#471 Closes #467
  NEWS.md
  R/Model-methods.R
  R/crmPack-package.R
  man/check_probabilities.Rd
  man/check_probability.Rd
  man/check_probability_range.Rd
  man/efficacy.Rd
  man/h_test_named_numeric.Rd
  man/nextBest.Rd
  tests/testthat/test-Model-methods.R
Labels: enhancement, cleanup

#475 Closes #472
  NAMESPACE
  R/checkmate.R
  _pkgdown.yaml
  man/check_length.Rd
Labels: cleanup

#476 Closes #473
  NAMESPACE
  NEWS.md
  R/Data-methods.R
  _pkgdown.yaml
  examples/Data-method-ngrid.R
  man/ngrid.Rd
  tests/testthat/test-Data-methods.R
Labels: enhancement
